spring:
  config.activate.on-profile: default
  sql.init.platform: h2
  web.resources.static-locations: file:./app/
cds:
  data-source.auto-config.enabled: false
  security:
    mock:
      default-users:
        enabled: false
      users:
        admin:
          name: admin
          password: admin
          roles: ADMIN
        user:
          name: vendor
          password: vendor
          roles: VENDOR
management:
  endpoint:
    health:
      show-components: always
      probes.enabled: true
  endpoints:
    web:
      exposure:
        include: health
  health:
    defaults.enabled: false
    ping.enabled: true
    db.enabled: true
